package org.gampiot.robok.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF904A48)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD8)
val md_theme_light_onPrimaryContainer = Color(0xFF3B080B)
val md_theme_light_secondary = Color(0xFF775655)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD8)
val md_theme_light_onSecondaryContainer = Color(0xFF2C1514)
val md_theme_light_tertiary = Color(0xFF735A2E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDEAA)
val md_theme_light_onTertiaryContainer = Color(0xFF271900)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFF8F7)
val md_theme_light_onBackground = Color(0xFF231919)
val md_theme_light_surface = Color(0xFFFFF8F7)
val md_theme_light_onSurface = Color(0xFF231919)
val md_theme_light_surfaceVariant = Color(0xFFF4DDDC)
val md_theme_light_onSurfaceVariant = Color(0xFF534342)
val md_theme_light_outline = Color(0xFF857372)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDEB)
val md_theme_light_inverseSurface = Color(0xFF382E2D)
val md_theme_light_inversePrimary = Color(0xFFFFB3B0)
val md_theme_light_surfaceTint = Color(0xFF904A48)
val md_theme_light_outlineVariant = Color(0xFFD7C1C0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB3B0)
val md_theme_dark_onPrimary = Color(0xFF571D1E)
val md_theme_dark_primaryContainer = Color(0xFF733332)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD8)
val md_theme_dark_secondary = Color(0xFFE7BDBA)
val md_theme_dark_onSecondary = Color(0xFF442928)
val md_theme_dark_secondaryContainer = Color(0xFF5D3F3E)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD8)
val md_theme_dark_tertiary = Color(0xFFE3C28C)
val md_theme_dark_onTertiary = Color(0xFF412D05)
val md_theme_dark_tertiaryContainer = Color(0xFF5A4319)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDEAA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1111)
val md_theme_dark_onBackground = Color(0xFFF0DEDD)
val md_theme_dark_surface = Color(0xFF1A1111)
val md_theme_dark_onSurface = Color(0xFFF0DEDD)
val md_theme_dark_surfaceVariant = Color(0xFF534342)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C1C0)
val md_theme_dark_outline = Color(0xFFA08C8B)
val md_theme_dark_inverseOnSurface = Color(0xFF382E2D)
val md_theme_dark_inverseSurface = Color(0xFFF0DEDD)
val md_theme_dark_inversePrimary = Color(0xFF904A48)
val md_theme_dark_surfaceTint = Color(0xFFFFB3B0)
val md_theme_dark_outlineVariant = Color(0xFF534342)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF2B4241)
